/*Version 2.6.7*/

#ifndef CN_ITEM_H
#define CN_ITEM_H 1  // mark it 0 if encoding error occurs
#if CN_ITEM_H
#define CN_C_0 "霆霓快雨·刻晴(雷)"
#define CN_C_1 "星天水镜·莫娜(水)"
#define CN_C_2 "冻冻回魂夜·七七(冰)"
#define CN_C_3 "晨曦的暗面·迪卢克(火)"
#define CN_C_4 "蒲公英骑士·琴(风)"
#define CN_C_5 "弓·阿莫斯之弓"
#define CN_C_6 "弓·天空之翼"
#define CN_C_7 "法器·四风原典"
#define CN_C_8 "法器·天空之卷"
#define CN_C_9 "长柄武器·和璞鸢"
#define CN_C_10 "长柄武器·天空之脊"
#define CN_C_11 "双手剑·狼的末路"
#define CN_C_12 "双手剑·天空之傲"
#define CN_C_13 "单手剑·天空之刃"
#define CN_C_14 "单手剑·风鹰剑"
#define CN_C_15 "棘冠恩典·罗莎莉亚(冰)"
#define CN_C_16 "燥热旋律·辛焱(火)"
#define CN_C_17 "无害甜度·砂糖(风)"
#define CN_C_18 "猫尾特调·迪奥娜(冰)"
#define CN_C_19 "雪融有踪·重云(冰)"
#define CN_C_20 "未受勋之花·诺艾尔(岩)"
#define CN_C_21 "命运试金石·班尼特(火)"
#define CN_C_22 "断罪皇女！！·菲谢尔(雷)"
#define CN_C_23 "掩月天权·凝光(岩)"
#define CN_C_24 "少年春衫薄·行秋(水)"
#define CN_C_25 "无冕的龙王·北斗(雷)"
#define CN_C_26 "万民百味·香菱(火)"
#define CN_C_27 "飞行冠军·安柏(火)"
#define CN_C_28 "狼少年·雷泽(雷)"
#define CN_C_29 "寒风剑士·凯亚(冰)"
#define CN_C_30 "闪耀偶像·芭芭拉(水)"
#define CN_C_31 "蔷薇魔女·丽莎(雷)"
#define CN_C_32 "弓·弓藏"
#define CN_C_33 "弓·祭礼弓"
#define CN_C_34 "弓·绝弦"
#define CN_C_35 "弓·西风猎弓"
#define CN_C_36 "法器·昭心"
#define CN_C_37 "法器·祭礼残章"
#define CN_C_38 "法器·流浪乐章"
#define CN_C_39 "法器·西风秘典"
#define CN_C_40 "长柄武器·西风长枪"
#define CN_C_41 "长柄武器·匣里灭辰"
#define CN_C_42 "双手剑·雨裁"
#define CN_C_43 "双手剑·祭礼大剑"
#define CN_C_44 "双手剑·钟剑"
#define CN_C_45 "双手剑·西风大剑"
#define CN_C_46 "单手剑·匣里龙吟"
#define CN_C_47 "单手剑·祭礼剑"
#define CN_C_48 "单手剑·笛剑"
#define CN_C_49 "单手剑·西风剑"
#define CN_C_50 "弓·猎弓"
#define CN_C_51 "弓·神射手之誓"
#define CN_C_52 "弓·鸦羽弓"
#define CN_C_53 "法器·翡玉法球"
#define CN_C_54 "法器·讨龙英杰谭"
#define CN_C_55 "法器·魔导绪论"
#define CN_C_56 "长柄武器·黑缨枪"
#define CN_C_57 "双手剑·以理服人"
#define CN_C_58 "双手剑·沐浴龙血的剑"
#define CN_C_59 "双手剑·铁影阔剑"
#define CN_C_60 "单手剑·飞天御剑"
#define CN_C_61 "单手剑·黎明神剑"
#define CN_C_62 "单手剑·冷刃"
#define CN_C_63 "风色诗人·温迪(风)"
#define CN_C_64 "逃跑的太阳·可莉(火)"
#define CN_C_65 "「公子」·达达利亚(水)"
#define CN_C_66 "尘世闲游·钟离(岩)"
#define CN_C_67 "白垩之子·阿贝多(岩)"
#define CN_C_68 "循循守月·甘雨(冰)"
#define CN_C_69 "护法夜叉·魈(风)"
#define CN_C_70 "雪霁梅香·胡桃(火)"
#define CN_C_71 "智明无邪·烟绯(火)"
#define CN_C_72 "浪沫的旋舞·优菈(冰)"
#define CN_C_73 "法器·尘世之锁"
#define CN_C_74 "长柄武器·贯虹之槊"
#define CN_C_75 "双手剑·无工之剑"
#define CN_C_76 "单手剑·斫峰之刃"
#define CN_C_77 "单手剑·磐岩结绿"
#define CN_C_78 "长柄武器·护摩之杖"
#define CN_C_79 "双手剑·千岩古剑"
#define CN_C_80 "长柄武器·千岩长枪"
#define CN_C_81 "弓·终末嗟叹之诗"
#define CN_C_82 "单手剑·暗巷闪光"
#define CN_C_83 "法器·暗巷的酒与诗"
#define CN_C_84 "弓·暗巷猎手"
#define CN_C_85 "双手剑·松籁响起之时"
#define CN_C_86 "红叶逐荒波·枫原万叶(风)"
#define CN_C_87 "单手剑·苍古自由之誓"
#define CN_C_88 "弓·幽夜华尔兹"
#define CN_C_89 "白鹭霜华·神里绫华(冰)"
#define CN_C_90 "琉焰华舞·宵宫(火)"
#define CN_C_91 "忍里之貉·早柚(风)"
#define CN_C_92 "单手剑·雾切之回光"
#define CN_C_93 "弓·飞雷之弦振"
#define CN_C_94 "真珠之智·珊瑚宫心海(水)"
#define CN_C_95 "黑羽鸣镝·九条裟罗(雷)"
#define CN_C_96 "一心净土·雷电将军(雷)"
#define CN_C_97 "长柄武器·薙草之稻光"
#define CN_C_98 "法器·不灭月华"
#define CN_C_99 "浮世笑百姿·八重神子(雷)"
#define CN_C_100 "渡来介者·托马(火)"
#define CN_C_101 "弓·冬极白星"
#define CN_C_102 "弓·曚云之月"
#define CN_C_103 "长柄武器·断浪长鳍"
#define CN_C_104 "双手剑·恶玉丸"
#define CN_C_105 "花坂豪快·荒泷一斗(岩)"
#define CN_C_106 "戎犬锵锵·五郎(岩)"
#define CN_C_107 "双手剑·赤角石溃杵"
#define CN_C_108 "红毹婵娟·云堇(岩)"
#define CN_C_109 "孤辰茕怀·申鹤(冰)"
#define CN_C_110 "长柄武器·息灾"
#define CN_C_111 "磐祭叶守·神里绫人(水)"
#define CN_C_112 "法器·神乐之真意"
#define CN_C_113 "单手剑·波乱月白经津"
#define CN_C_114 "兰生幽谷·夜兰(水)"
#define CN_C_115 "烦恼刈除·久岐忍(雷)"
#define CN_C_116 "心朝乂安·鹿野院平藏(风)"
#define CN_C_117 "弓·若水"
#define CN_C_118 "Placeholder"
#define CN_C_119 "Placeholder"
#define CN_C_120 "Placeholder"
#define CN_C_121 "Placeholder"
#define CN_C_122 "Placeholder"
#define CN_C_123 "Placeholder"
#define CN_C_124 "Placeholder"
#define CN_C_125 "Placeholder"
#define CN_C_126 "Placeholder"
#define CN_C_127 "Placeholder"
#define CN_X_0 "刻晴"
#define CN_X_1 "莫娜"
#define CN_X_2 "七七"
#define CN_X_3 "迪卢克"
#define CN_X_4 "琴"
#define CN_X_5 "阿莫斯之弓"
#define CN_X_6 "天空之翼"
#define CN_X_7 "四风原典"
#define CN_X_8 "天空之卷"
#define CN_X_9 "和璞鸢"
#define CN_X_10 "天空之脊"
#define CN_X_11 "狼的末路"
#define CN_X_12 "天空之傲"
#define CN_X_13 "天空之刃"
#define CN_X_14 "风鹰剑"
#define CN_X_15 "罗莎莉亚"
#define CN_X_16 "辛焱"
#define CN_X_17 "砂糖"
#define CN_X_18 "迪奥娜"
#define CN_X_19 "重云"
#define CN_X_20 "诺艾尔"
#define CN_X_21 "班尼特"
#define CN_X_22 "菲谢尔"
#define CN_X_23 "凝光"
#define CN_X_24 "行秋"
#define CN_X_25 "北斗"
#define CN_X_26 "香菱"
#define CN_X_27 "安柏"
#define CN_X_28 "雷泽"
#define CN_X_29 "凯亚"
#define CN_X_30 "芭芭拉"
#define CN_X_31 "丽莎"
#define CN_X_32 "弓藏"
#define CN_X_33 "祭礼弓"
#define CN_X_34 "绝弦"
#define CN_X_35 "西风猎弓"
#define CN_X_36 "昭心"
#define CN_X_37 "祭礼残章"
#define CN_X_38 "流浪乐章"
#define CN_X_39 "西风秘典"
#define CN_X_40 "西风长枪"
#define CN_X_41 "匣里灭辰"
#define CN_X_42 "雨裁"
#define CN_X_43 "祭礼大剑"
#define CN_X_44 "钟剑"
#define CN_X_45 "西风大剑"
#define CN_X_46 "匣里龙吟"
#define CN_X_47 "祭礼剑"
#define CN_X_48 "笛剑"
#define CN_X_49 "西风剑"
#define CN_X_50 "猎弓"
#define CN_X_51 "神射手之誓"
#define CN_X_52 "鸦羽弓"
#define CN_X_53 "翡玉法球"
#define CN_X_54 "讨龙英杰谭"
#define CN_X_55 "魔导绪论"
#define CN_X_56 "黑缨枪"
#define CN_X_57 "以理服人"
#define CN_X_58 "沐浴龙血的剑"
#define CN_X_59 "铁影阔剑"
#define CN_X_60 "飞天御剑"
#define CN_X_61 "黎明神剑"
#define CN_X_62 "冷刃"
#define CN_X_63 "温迪"
#define CN_X_64 "可莉"
#define CN_X_65 "达达利亚"
#define CN_X_66 "钟离"
#define CN_X_67 "阿贝多"
#define CN_X_68 "甘雨"
#define CN_X_69 "魈"
#define CN_X_70 "胡桃"
#define CN_X_71 "烟绯"
#define CN_X_72 "优菈"
#define CN_X_73 "尘世之锁"
#define CN_X_74 "贯虹之槊"
#define CN_X_75 "无工之剑"
#define CN_X_76 "斫峰之刃"
#define CN_X_77 "磐岩结绿"
#define CN_X_78 "护摩之杖"
#define CN_X_79 "千岩古剑"
#define CN_X_80 "千岩长枪"
#define CN_X_81 "终末嗟叹之诗"
#define CN_X_82 "暗巷闪光"
#define CN_X_83 "暗巷的酒与诗"
#define CN_X_84 "暗巷猎手"
#define CN_X_85 "松籁响起之时"
#define CN_X_86 "枫原万叶"
#define CN_X_87 "苍古自由之誓"
#define CN_X_88 "幽夜华尔兹"
#define CN_X_89 "神里绫华"
#define CN_X_90 "宵宫"
#define CN_X_91 "早柚"
#define CN_X_92 "雾切之回光"
#define CN_X_93 "飞雷之弦振"
#define CN_X_94 "珊瑚宫心海"
#define CN_X_95 "九条裟罗"
#define CN_X_96 "雷电将军"
#define CN_X_97 "薙草之稻光"
#define CN_X_98 "不灭月华"
#define CN_X_99 "八重神子"
#define CN_X_100 "托马"
#define CN_X_101 "冬极白星"
#define CN_X_102 "曚云之月"
#define CN_X_103 "断浪长鳍"
#define CN_X_104 "恶玉丸"
#define CN_X_105 "荒泷一斗"
#define CN_X_106 "五郎"
#define CN_X_107 "赤角石溃杵"
#define CN_X_108 "云堇"
#define CN_X_109 "申鹤"
#define CN_X_110 "息灾"
#define CN_X_111 "神里绫人"
#define CN_X_112 "神乐之真意"
#define CN_X_113 "波乱月白经津"
#define CN_X_114 "夜兰"
#define CN_X_115 "久岐忍"
#define CN_X_116 "鹿野院平藏"
#define CN_X_117 "若水"
#define CN_X_118 "Placeholder"
#define CN_X_119 "Placeholder"
#define CN_X_120 "Placeholder"
#define CN_X_121 "Placeholder"
#define CN_X_122 "Placeholder"
#define CN_X_123 "Placeholder"
#define CN_X_124 "Placeholder"
#define CN_X_125 "Placeholder"
#define CN_X_126 "Placeholder"
#define CN_X_127 "Placeholder"
#define CN_D_0                                                                                                         \
  "璃月七星之一，玉衡星。对「帝君一言而决的璃月」颇有微词——但实际上，神挺欣赏" \
  "她这样的人。"
#define CN_D_1                                                                                                      \
  "神秘的少女占星术士，声称自己是「伟大的占星术士莫娜」，拥有与名号相符的不俗" \
  "实力，博学而高傲。"
#define CN_D_2                                                                                                      \
  "药庐「不卜庐」的采药姑娘兼学徒，面色苍白如纸的不死之人。话很少，也没有什么" \
  "表情。"
#define CN_D_3 "坐拥蒙德大半酒业的贵公子，财力、人望、能力都令人无法小觑。"
#define CN_D_4 "正直严谨的蒲公英骑士，蒙德西风骑士团的代理团长。"
#define CN_D_5                                                                                                         \
  "极为古老的弓。即使原主不复存在，其中蕴藏之力依旧——那种力量无主，却在万物当" \
  "中。距离心系之物越是遥远，那种力量愈是剧烈。"
#define CN_D_6                                                                                                      \
  "象征风龙身为风之神眷属的大弓。释弦时的鸣声是风之神的偏爱，蕴含苍空与长风的" \
  "力量。"
#define CN_D_7                                                                                                      \
  "崇信风的无名先民所写的教典珍本。数千年流传的信仰之力得到了风的青睐，饱含祝" \
  "福与力量。"
#define CN_D_8                                                                                                      \
  "象征风龙与其主风之神的云图集。细致记载了北地天空的风与云，蕴含苍空与长风的" \
  "力量。"
#define CN_D_9 "魔神翡玉化作的长枪，拥有刺杀远古海兽的沉重与锋利。"
#define CN_D_10 \
  "象征风龙坚定决心的长枪。直挺的枪杆直指天穹，蕴含苍空与长风的力量。"
#define CN_D_11                                                                                                     \
  "狼的骑士所使的大剑。原本只是城中铁匠赠予的厚重的铁片，却在他与狼的情谊中，" \
  "获得神话般的力量。"
#define CN_D_12                                                                                                     \
  "象征风龙的骄傲广布长空的双手剑。挥舞时的低吟是风龙的气势，蕴含苍空与长风的" \
  "力量。"
#define CN_D_13                                                                                                     \
  "象征风龙的荣誉的骑士剑，如今失而复得。剑脊上吹息着风之神的赐福，蕴含苍空与" \
  "长风的力量。"
#define CN_D_14                                                                                                     \
  "西风骑士团的灵魂。历经千年仍在呼唤你卷起正义之风，祓除奸邪，一如上一位挥舞" \
  "此剑的女杰。"
#define CN_D_15 \
  "除了打扮哪里都不像神职人员的修女。冷淡的言行中透着锐利。总是单独行动。"
#define CN_D_16 "璃月港唯一的摇滚乐手，以音乐和热情歌颂着对「成见」的反抗。"
#define CN_D_17 "对万物充满好奇的炼金术士，「生物炼金」学派的研究者。"
#define CN_D_18 "遗传了稀薄的「非人」血统的少女，「猫尾酒馆」的超人气调酒师。"
#define CN_D_19 "驱邪世家出身的年轻方士，为压制自身的「纯阳之体」费尽心思。"
#define CN_D_20 "「西风骑士团」的可靠女仆，梦想有一天能成为正式的骑士。"
#define CN_D_21 "蒙德的冒险家少年，拥有与他的善良毫不相称的霉运。"
#define CN_D_22 "自称「断罪之皇女」，与名为奥兹的漆黑夜鸦同行的神秘少女。"
#define CN_D_23 \
  "「璃月七星」中的「天权」，其名下财富之多，全大陆鲜有人能望其项背。"
#define CN_D_24 "经常能在书摊看到的少年人。手执长剑，胸中常怀侠义之心。"
#define CN_D_25 "武装船队「南十字」的首领，豪快的大姐头。"
#define CN_D_26 \
  "来自璃月，名声在外的少女厨师，对料理之道极具热情，拿手麻辣菜肴堪称一绝。"
#define CN_D_27 "永远充满活力的女孩，骑士团最优秀，同时也是最后的侦察骑士。"
#define CN_D_28                                                                                                     \
  "住在蒙德地区奔狼领，远离城市与人群，和狼一同生活的少年。直觉锐利，身姿迅捷" \
  "。"
#define CN_D_29 "异国面容的剑斗士，西风骑士团的头脑派人物。"
#define CN_D_30 \
  "蒙德城的大家都喜欢芭芭拉。「偶像」这个词是她从一本杂志里看到的。"
#define CN_D_31 "慵懒而博学的图书管理员，须弥教令院「两百年一见」的天才毕业生"
#define CN_D_32 "布满锈迹的铁造大弓，一般人根本拿不动，遑论引弓放矢。"
#define CN_D_33                                                                                                     \
  "在漫长岁月中石化的道具猎弓，上面的仪式性装饰依然清晰可见。拥有受时间之风冲" \
  "刷的祝福力量。"
#define CN_D_34 "曾经作为乐器大放异彩的弓。如今已经不再能令人起舞。"
#define CN_D_35 "西风骑士团的制式反曲弓，只有杰出的弓手能与它的杰出性能相衬。"
#define CN_D_36 "幽暗的琉璃宝珠，传说中拥有洞察人心清白的力量。"
#define CN_D_37                                                                                                     \
  "经历漫长岁月的剧本，记载着的颂词和剧本已经无法辨认。被下了受时间之风侵蚀毁" \
  "坏的诅咒。"
#define CN_D_38 \
  "记载着歌谱的厚重记事簿。尽管遭受了虫蛀和风化，残留的手迹仍透露出力量。"
#define CN_D_39 "西风骑士团的学者间流传的秘典，记载着元素与物质的道理和力量。"
#define CN_D_40 "西风骑士团的制式长枪。枪杆直挺，枪尖轻风流溢。"
#define CN_D_41 "金龙缠绕的长枪，轻快锐利无比。大抵真能轻易屠龙。"
#define CN_D_42 "散发着黯淡荧光的无锋大剑，纯粹以气势和力量碾碎敌人。"
#define CN_D_43                                                                                                     \
  "在漫长岁月中石化的道具大剑，上面的仪式性装饰依然清晰可见。拥有受时间之风冲" \
  "刷的祝福力量。"
#define CN_D_44 "装有时钟的厚重大剑，其中的计时机关早已被破坏。"
#define CN_D_45 "西风骑士团的重型仪式剑。能轻易导出元素力量，具有卓越的破坏力。"
#define CN_D_46 "雕饰浮华的利刃，却丝毫不损它的柔韧与锋锐。破空之声有如龙吟。"
#define CN_D_47                                                                                                     \
  "在漫长岁月中石化的道具剑，上面的仪式性装饰依然清晰可见。拥有受时间之风冲刷" \
  "的祝福力量。"
#define CN_D_48 "细剑的锈迹下透露出原本华丽的装饰，挥舞时轻若无物。"
#define CN_D_49 "西风骑士团的制式长剑。轻快锐利之余，也能轻易导出元素力量。"
#define CN_D_50                                                                                                     \
  "其实就是一把弓。在无数的改进和实验中，发明出究极弹弓的人发现自己做了一把弓" \
  "。"
#define CN_D_51                                                                                                     \
  "据说曾属于技艺高强的射手，是一把上好的弓。因为散发出强烈的气息，难以用于狩" \
  "猎。"
#define CN_D_52 \
  "相传渡鸦是死的使者。将鸦羽装饰在弓臂上，射出的每一箭都宣告着猎物的终末。"
#define CN_D_53                                                                                                     \
  "由璃月北郊绝云间出产的硬玉雕琢而成的法器。小巧轻盈，经久耐用，江湖人称「翡" \
  "玉丸」。"
#define CN_D_54                                                                                                     \
  "五名英雄踏上屠龙征途的虚构故事。文笔很差，结构散乱。失败的教训是这本书所拥" \
  "有的伟大力量。"
#define CN_D_55 "第十二版。结合时代发展加注了新内容，并修订了第十一版的错别字。"
#define CN_D_56 "解决了白缨容易弄脏问题的绝世好枪。"
#define CN_D_57 "精钢打造的趁手大铁棒子。最好的理论依据。"
#define CN_D_58                                                                                                     \
  "据说是北方英雄浸过龙血的钢铁大剑，有刀枪不入的神力…这种护佑并不会延伸到挥" \
  "舞它的人身上。"
#define CN_D_59                                                                                                     \
  "这把剑是著名的光之狮艾伦德林的佩剑的仿品。握紧它，感受传说中大英雄的力量吧" \
  "！注意：幻想请适度。"
#define CN_D_60 "可靠的钢剑，传说著名的「御剑公子」曾试图借助它飞天。"
#define CN_D_61                                                                                                     \
  "一把曾经耀若朝阳的宝剑，掌握它的人会获得「自我感觉良好」的力量加持。剑身上" \
  "的发光材料已经褪去。"
#define CN_D_62 "多层锻打的精钢铸就的可靠兵器，曾见证旧主诸多冒险奇谭。"
#define CN_D_63 "蒙德城诸多吟游诗人中的一位，自由自在地穿行在街头巷尾。"
#define CN_D_64 "西风骑士团禁闭室的常客，蒙德的爆破大师。人称「逃跑的太阳」。"
#define CN_D_65 "愚人众执行官第十一位，「公子」，其战绩威名远扬。"
#define CN_D_66 "被「往生堂」请来的神秘客人，知识渊博，对各种事物都颇有见地。"
#define CN_D_67 \
  "西风骑士团首席炼金术士兼调查小队队长，被称做「白垩之子」的天才。"
#define CN_D_68 "月海亭的秘书，体内流淌着仙兽「麒麟」的血脉。"
#define CN_D_69 \
  "守护璃月的仙人，「夜叉」。美号「降魔大圣」，妙称「护法夜叉大将」。"
#define CN_D_70 "「往生堂」七十七代堂主，年纪轻轻就已主掌璃月的葬仪事务。"
#define CN_D_71 "活跃在璃月港的知名律法咨询师，混有仙兽血脉的精明少女。"
#define CN_D_72                                                                                                     \
  "古老家族出身的「浪花骑士」，西风骑士团游击小队队长。身为旧贵族后裔却加入了" \
  "堪称死对头的西风骑士团，该事件至今仍是蒙德一大谜团。"
#define CN_D_73 "蕴含着某种悠远记忆的石锁，随着无穷的变换透露出其中的力量。"
#define CN_D_74 \
  "或许能贯穿一切的锋利长枪。挥舞当中，仿佛能见到空气被枪尖划破的裂痕。"
#define CN_D_75 "能靖祛妖魔奸佞，仿佛有神威的无锋大剑。"
#define CN_D_76 "传说中象征着某一则特定契约的利刃，曾经斩落过山岳的尖端。"
#define CN_D_77 "由纯净的翠玉精琢细雕而成的仪礼宝剑，挥舞时剑风中似有叹息之声。"
#define CN_D_78 "在早已失落的古老祭仪中，使用的朱赤「柴火杖」。"
#define CN_D_79 "以璃月的基岩为原料削凿成的厚重大剑。"
#define CN_D_80 "取孤云阁的岩片精工打造的长枪，枪尖坚固无比。"
#define CN_D_81 "如同诗人的乐器一般优美的弓，放出的箭矢如同叹息声一般穿透人心。"
#define CN_D_82 "有着黑夜颜色的笔直长剑，曾属于穿行于暗巷的盗贼。"
#define CN_D_83 \
  "过去贵族时代流行的歌谱，作者已无从考究。其中记载了某位侠盗的故事…"
#define CN_D_84 "外形精巧奢华的长弓，曾属于某位从未被抓获的义贼。"
#define CN_D_85 \
  "如同翻弄草木的息吹一般轻盈的大剑，如同吹倒树木的飓风一般摧枯拉朽的武器。"
#define CN_D_86                                                                                                     \
  "来自稻妻的浪人武士，如今栖身于璃月船队「南十字」中。性情温和而洒脱，心中埋" \
  "藏着许多往事。"
#define CN_D_87 \
  "如同悠古的歌声一般苍蓝的直剑，如同风之国土自由的誓言一般锐利的武器。"
#define CN_D_88 "有着如同罪与幻想之夜一般颜色的弓。"
#define CN_D_89 "稻妻「社奉行」神里家的大小姐。端庄而文雅，聪慧又坚韧。"
#define CN_D_90 \
  "「长野原烟花店」店长，「夏祭的女王」，将人们的愿望寄托于烟花中的能工巧匠。"
#define CN_D_91 "隶属于「终末番」的忍者。身形小巧，总像没睡饱一样。"
#define CN_D_92 "闪烁着凄烈紫光的太刀。名之为「回光」是因为一度破碎的过去。"
#define CN_D_93 "曾由将军御赐的长弓，闪烁着永不熄灭的雷光。"
#define CN_D_94 "海祇岛的「现人神巫女」，统管海祇岛各项事宜的少女。"
#define CN_D_95 "「天领奉行」的大将，杀伐果断，骁勇善战。"
#define CN_D_96 "其身为御建鸣神主尊大御所大人，许稻妻人民以亘古不变之「永恒」。"
#define CN_D_97 "用于「斩草」的薙刀。对向此物之军势，也会如苇草般倒下吧…"
#define CN_D_98 "出自深海的美玉之环，闪烁着清澈如月的光泽，一如遥远往昔。"
#define CN_D_99                                                                                                     \
  "鸣神大社的宫司大人，兼任「八重堂」总编。艳丽动人的外表下藏着令人意想不到的" \
  "聪慧与狡黠。"
#define CN_D_100 "神里家的家政官，活跃在稻妻的「地头蛇」。"
#define CN_D_101 "如同深冬坚冰一样尖锐的无垢之弓。"
#define CN_D_102 "出自螺钿与珊瑚的精美战弓，月色的弓臂上流动着凄然的光彩。"
#define CN_D_103 "以海渊之下的闪亮材质打造而成的薙刀，一度曾为天狗一族所有。"
#define CN_D_104 \
  "传说中「恶王」的爱刀，刀身庞大雄伟，但挥舞起来却出乎意料地轻便。"
#define CN_D_105                                                                                                    \
  "活跃在稻妻城花见坂的「荒泷派」初代目头领。什么，从没听说过荒泷派？你是想找" \
  "茬吗？"
#define CN_D_106 "海祇岛军的大将，深受部下信赖。"
#define CN_D_107                                                                                                    \
  "依据过去的主人的说法，这是何等鬼怪精妖都能打跑的大杵「赤角石见石溃金涂金啮" \
  "御狮子」。"
#define CN_D_108 \
  "集剧作与演唱能力于一身的璃月戏曲名角。风格自成一派，雅致柔美，恰如其人。"
#define CN_D_109 \
  "气质出尘的仙家子弟。隐修在璃月群山之间，个性也如仙人般淡漠疏离。"
#define CN_D_110 "由奇异晶石打造成的锋锐利器。幽幽蓝光似乎诉说着无尽往事。"
#define CN_D_111 "社奉行神里家年轻有为的现任家主，为人温雅有礼，处事颇有手段。"
#define CN_D_112 "表演神乐之舞时所用的神铃，为宫司所赐福。神樱之香萦绕其上。"
#define CN_D_113 \
  "经津传奉命锻造的名作。因其如汹涌海涛般的气度，而得「波乱」之名。"
#define CN_D_114 "夜兰"
#define CN_D_115 "久岐忍"
#define CN_D_116 "鹿野院平藏"
#define CN_D_117 "若水"
#define CN_D_118 "Placeholder"
#define CN_D_119 "Placeholder"
#define CN_D_120 "Placeholder"
#define CN_D_121 "Placeholder"
#define CN_D_122 "Placeholder"
#define CN_D_123 "Placeholder"
#define CN_D_124 "Placeholder"
#define CN_D_125 "Placeholder"
#define CN_D_126 "Placeholder"
#define CN_D_127 "Placeholder"

#endif

#endif
