/*Version 3.0*/

#ifndef CN_ITEM_H
#define CN_ITEM_H 1  // mark it 0 if encoding error occurs
#if CN_ITEM_H
#define CN_C_0 "霆霓快雨·刻晴(雷)"
#define CN_C_1 "星天水镜·莫娜(水)"
#define CN_C_2 "冻冻回魂夜·七七(冰)"
#define CN_C_3 "晨曦的暗面·迪卢克(火)"
#define CN_C_4 "蒲公英骑士·琴(风)"
#define CN_C_5 "弓·阿莫斯之弓"
#define CN_C_6 "弓·天空之翼"
#define CN_C_7 "法器·四风原典"
#define CN_C_8 "法器·天空之卷"
#define CN_C_9 "长柄武器·和璞鸢"
#define CN_C_10 "长柄武器·天空之脊"
#define CN_C_11 "双手剑·狼的末路"
#define CN_C_12 "双手剑·天空之傲"
#define CN_C_13 "单手剑·天空之刃"
#define CN_C_14 "单手剑·风鹰剑"
#define CN_C_15 "棘冠恩典·罗莎莉亚(冰)"
#define CN_C_16 "燥热旋律·辛焱(火)"
#define CN_C_17 "无害甜度·砂糖(风)"
#define CN_C_18 "猫尾特调·迪奥娜(冰)"
#define CN_C_19 "雪融有踪·重云(冰)"
#define CN_C_20 "未受勋之花·诺艾尔(岩)"
#define CN_C_21 "命运试金石·班尼特(火)"
#define CN_C_22 "断罪皇女！！·菲谢尔(雷)"
#define CN_C_23 "掩月天权·凝光(岩)"
#define CN_C_24 "少年春衫薄·行秋(水)"
#define CN_C_25 "无冕的龙王·北斗(雷)"
#define CN_C_26 "万民百味·香菱(火)"
#define CN_C_27 "飞行冠军·安柏(火)"
#define CN_C_28 "狼少年·雷泽(雷)"
#define CN_C_29 "寒风剑士·凯亚(冰)"
#define CN_C_30 "闪耀偶像·芭芭拉(水)"
#define CN_C_31 "蔷薇魔女·丽莎(雷)"
#define CN_C_32 "弓·弓藏"
#define CN_C_33 "弓·祭礼弓"
#define CN_C_34 "弓·绝弦"
#define CN_C_35 "弓·西风猎弓"
#define CN_C_36 "法器·昭心"
#define CN_C_37 "法器·祭礼残章"
#define CN_C_38 "法器·流浪乐章"
#define CN_C_39 "法器·西风秘典"
#define CN_C_40 "长柄武器·西风长枪"
#define CN_C_41 "长柄武器·匣里灭辰"
#define CN_C_42 "双手剑·雨裁"
#define CN_C_43 "双手剑·祭礼大剑"
#define CN_C_44 "双手剑·钟剑"
#define CN_C_45 "双手剑·西风大剑"
#define CN_C_46 "单手剑·匣里龙吟"
#define CN_C_47 "单手剑·祭礼剑"
#define CN_C_48 "单手剑·笛剑"
#define CN_C_49 "单手剑·西风剑"
#define CN_C_50 "弓·猎弓"
#define CN_C_51 "弓·神射手之誓"
#define CN_C_52 "弓·鸦羽弓"
#define CN_C_53 "法器·翡玉法球"
#define CN_C_54 "法器·讨龙英杰谭"
#define CN_C_55 "法器·魔导绪论"
#define CN_C_56 "长柄武器·黑缨枪"
#define CN_C_57 "双手剑·以理服人"
#define CN_C_58 "双手剑·沐浴龙血的剑"
#define CN_C_59 "双手剑·铁影阔剑"
#define CN_C_60 "单手剑·飞天御剑"
#define CN_C_61 "单手剑·黎明神剑"
#define CN_C_62 "单手剑·冷刃"
#define CN_C_63 "风色诗人·温迪(风)"
#define CN_C_64 "逃跑的太阳·可莉(火)"
#define CN_C_65 "「公子」·达达利亚(水)"
#define CN_C_66 "尘世闲游·钟离(岩)"
#define CN_C_67 "白垩之子·阿贝多(岩)"
#define CN_C_68 "循循守月·甘雨(冰)"
#define CN_C_69 "护法夜叉·魈(风)"
#define CN_C_70 "雪霁梅香·胡桃(火)"
#define CN_C_71 "智明无邪·烟绯(火)"
#define CN_C_72 "浪沫的旋舞·优菈(冰)"
#define CN_C_73 "法器·尘世之锁"
#define CN_C_74 "长柄武器·贯虹之槊"
#define CN_C_75 "双手剑·无工之剑"
#define CN_C_76 "单手剑·斫峰之刃"
#define CN_C_77 "单手剑·磐岩结绿"
#define CN_C_78 "长柄武器·护摩之杖"
#define CN_C_79 "双手剑·千岩古剑"
#define CN_C_80 "长柄武器·千岩长枪"
#define CN_C_81 "弓·终末嗟叹之诗"
#define CN_C_82 "单手剑·暗巷闪光"
#define CN_C_83 "法器·暗巷的酒与诗"
#define CN_C_84 "弓·暗巷猎手"
#define CN_C_85 "双手剑·松籁响起之时"
#define CN_C_86 "红叶逐荒波·枫原万叶(风)"
#define CN_C_87 "单手剑·苍古自由之誓"
#define CN_C_88 "弓·幽夜华尔兹"
#define CN_C_89 "白鹭霜华·神里绫华(冰)"
#define CN_C_90 "琉焰华舞·宵宫(火)"
#define CN_C_91 "忍里之貉·早柚(风)"
#define CN_C_92 "单手剑·雾切之回光"
#define CN_C_93 "弓·飞雷之弦振"
#define CN_C_94 "真珠之智·珊瑚宫心海(水)"
#define CN_C_95 "黑羽鸣镝·九条裟罗(雷)"
#define CN_C_96 "一心净土·雷电将军(雷)"
#define CN_C_97 "长柄武器·薙草之稻光"
#define CN_C_98 "法器·不灭月华"
#define CN_C_99 "浮世笑百姿·八重神子(雷)"
#define CN_C_100 "渡来介者·托马(火)"
#define CN_C_101 "弓·冬极白星"
#define CN_C_102 "弓·曚云之月"
#define CN_C_103 "长柄武器·断浪长鳍"
#define CN_C_104 "双手剑·恶玉丸"
#define CN_C_105 "花坂豪快·荒泷一斗(岩)"
#define CN_C_106 "戎犬锵锵·五郎(岩)"
#define CN_C_107 "双手剑·赤角石溃杵"
#define CN_C_108 "红毹婵娟·云堇(岩)"
#define CN_C_109 "孤辰茕怀·申鹤(冰)"
#define CN_C_110 "长柄武器·息灾"
#define CN_C_111 "磐祭叶守·神里绫人(水)"
#define CN_C_112 "法器·神乐之真意"
#define CN_C_113 "单手剑·波乱月白经津"
#define CN_C_114 "兰生幽谷·夜兰(水)"
#define CN_C_115 "烦恼刈除·久岐忍(雷)"
#define CN_C_116 "心朝乂安·鹿野院平藏(风)"
#define CN_C_117 "弓·若水"
#define CN_C_118 "萃念初蘖·柯莱(草)"
#define CN_C_119 "浅蔚轻行·提纳里(草)"
#define CN_C_120 "梦园藏金·多莉(雷)"
#define CN_C_121 "艾尔海森"
#define CN_C_122 "迪希雅"
#define CN_C_123 "莲光落舞筵·妮露(水)"
#define CN_C_124 "纳西妲"
#define CN_C_125 "缄秘的裁遣·赛诺(雷)"
#define CN_C_126 "浮金的誓愿·坎蒂丝(水)"
#define CN_C_127 "弓·猎人之径"
#define CN_C_128 "Placeholder"
#define CN_C_129 "Placeholder"
#define CN_C_130 "Placeholder"
#define CN_C_131 "Placeholder"
#define CN_C_132 "Placeholder"
#define CN_C_133 "Placeholder"
#define CN_C_134 "Placeholder"
#define CN_C_135 "Placeholder"
#define CN_C_136 "Placeholder"
#define CN_C_137 "Placeholder"
#define CN_C_138 "Placeholder"
#define CN_C_139 "Placeholder"
#define CN_C_140 "Placeholder"
#define CN_C_141 "Placeholder"
#define CN_C_142 "Placeholder"
#define CN_C_143 "Placeholder"
#define CN_C_144 "Placeholder"
#define CN_C_145 "Placeholder"
#define CN_C_146 "Placeholder"
#define CN_C_147 "Placeholder"
#define CN_C_148 "Placeholder"
#define CN_C_149 "Placeholder"
#define CN_C_150 "Placeholder"
#define CN_C_151 "Placeholder"
#define CN_C_152 "Placeholder"
#define CN_C_153 "Placeholder"
#define CN_C_154 "Placeholder"
#define CN_C_155 "Placeholder"
#define CN_C_156 "Placeholder"
#define CN_C_157 "Placeholder"
#define CN_C_158 "Placeholder"
#define CN_C_159 "Placeholder"
#define CN_C_160 "Placeholder"
#define CN_C_161 "Placeholder"
#define CN_C_162 "Placeholder"
#define CN_C_163 "Placeholder"
#define CN_C_164 "Placeholder"
#define CN_C_165 "Placeholder"
#define CN_C_166 "Placeholder"
#define CN_C_167 "Placeholder"
#define CN_C_168 "Placeholder"
#define CN_C_169 "Placeholder"
#define CN_C_170 "Placeholder"
#define CN_C_171 "Placeholder"
#define CN_C_172 "Placeholder"
#define CN_C_173 "Placeholder"
#define CN_C_174 "Placeholder"
#define CN_C_175 "Placeholder"
#define CN_C_176 "Placeholder"
#define CN_C_177 "Placeholder"
#define CN_C_178 "Placeholder"
#define CN_C_179 "Placeholder"
#define CN_C_180 "Placeholder"
#define CN_C_181 "Placeholder"
#define CN_C_182 "Placeholder"
#define CN_C_183 "Placeholder"
#define CN_C_184 "Placeholder"
#define CN_C_185 "Placeholder"
#define CN_C_186 "Placeholder"
#define CN_C_187 "Placeholder"
#define CN_C_188 "Placeholder"
#define CN_C_189 "Placeholder"
#define CN_C_190 "Placeholder"
#define CN_C_191 "Placeholder"
#define CN_C_192 "Placeholder"
#define CN_C_193 "Placeholder"
#define CN_C_194 "Placeholder"
#define CN_C_195 "Placeholder"
#define CN_C_196 "Placeholder"
#define CN_C_197 "Placeholder"
#define CN_C_198 "Placeholder"
#define CN_C_199 "Placeholder"
#define CN_C_200 "Placeholder"
#define CN_C_201 "Placeholder"
#define CN_C_202 "Placeholder"
#define CN_C_203 "Placeholder"
#define CN_C_204 "Placeholder"
#define CN_C_205 "Placeholder"
#define CN_C_206 "Placeholder"
#define CN_C_207 "Placeholder"
#define CN_C_208 "Placeholder"
#define CN_C_209 "Placeholder"
#define CN_C_210 "Placeholder"
#define CN_C_211 "Placeholder"
#define CN_C_212 "Placeholder"
#define CN_C_213 "Placeholder"
#define CN_C_214 "Placeholder"
#define CN_C_215 "Placeholder"
#define CN_C_216 "Placeholder"
#define CN_C_217 "Placeholder"
#define CN_C_218 "Placeholder"
#define CN_C_219 "Placeholder"
#define CN_C_220 "Placeholder"
#define CN_C_221 "Placeholder"
#define CN_C_222 "Placeholder"
#define CN_C_223 "Placeholder"
#define CN_C_224 "Placeholder"
#define CN_C_225 "Placeholder"
#define CN_C_226 "Placeholder"
#define CN_C_227 "Placeholder"
#define CN_C_228 "Placeholder"
#define CN_C_229 "Placeholder"
#define CN_C_230 "Placeholder"
#define CN_C_231 "Placeholder"
#define CN_C_232 "Placeholder"
#define CN_C_233 "Placeholder"
#define CN_C_234 "Placeholder"
#define CN_C_235 "Placeholder"
#define CN_C_236 "Placeholder"
#define CN_C_237 "Placeholder"
#define CN_C_238 "Placeholder"
#define CN_C_239 "Placeholder"
#define CN_C_240 "Placeholder"
#define CN_C_241 "Placeholder"
#define CN_C_242 "Placeholder"
#define CN_C_243 "Placeholder"
#define CN_C_244 "Placeholder"
#define CN_C_245 "Placeholder"
#define CN_C_246 "Placeholder"
#define CN_C_247 "Placeholder"
#define CN_C_248 "Placeholder"
#define CN_C_249 "Placeholder"
#define CN_C_250 "Placeholder"
#define CN_C_251 "Placeholder"
#define CN_C_252 "Placeholder"
#define CN_C_253 "Placeholder"
#define CN_C_254 "Placeholder"
#define CN_C_255 "Placeholder"
#define CN_X_0 "刻晴"
#define CN_X_1 "莫娜"
#define CN_X_2 "七七"
#define CN_X_3 "迪卢克"
#define CN_X_4 "琴"
#define CN_X_5 "阿莫斯之弓"
#define CN_X_6 "天空之翼"
#define CN_X_7 "四风原典"
#define CN_X_8 "天空之卷"
#define CN_X_9 "和璞鸢"
#define CN_X_10 "天空之脊"
#define CN_X_11 "狼的末路"
#define CN_X_12 "天空之傲"
#define CN_X_13 "天空之刃"
#define CN_X_14 "风鹰剑"
#define CN_X_15 "罗莎莉亚"
#define CN_X_16 "辛焱"
#define CN_X_17 "砂糖"
#define CN_X_18 "迪奥娜"
#define CN_X_19 "重云"
#define CN_X_20 "诺艾尔"
#define CN_X_21 "班尼特"
#define CN_X_22 "菲谢尔"
#define CN_X_23 "凝光"
#define CN_X_24 "行秋"
#define CN_X_25 "北斗"
#define CN_X_26 "香菱"
#define CN_X_27 "安柏"
#define CN_X_28 "雷泽"
#define CN_X_29 "凯亚"
#define CN_X_30 "芭芭拉"
#define CN_X_31 "丽莎"
#define CN_X_32 "弓藏"
#define CN_X_33 "祭礼弓"
#define CN_X_34 "绝弦"
#define CN_X_35 "西风猎弓"
#define CN_X_36 "昭心"
#define CN_X_37 "祭礼残章"
#define CN_X_38 "流浪乐章"
#define CN_X_39 "西风秘典"
#define CN_X_40 "西风长枪"
#define CN_X_41 "匣里灭辰"
#define CN_X_42 "雨裁"
#define CN_X_43 "祭礼大剑"
#define CN_X_44 "钟剑"
#define CN_X_45 "西风大剑"
#define CN_X_46 "匣里龙吟"
#define CN_X_47 "祭礼剑"
#define CN_X_48 "笛剑"
#define CN_X_49 "西风剑"
#define CN_X_50 "猎弓"
#define CN_X_51 "神射手之誓"
#define CN_X_52 "鸦羽弓"
#define CN_X_53 "翡玉法球"
#define CN_X_54 "讨龙英杰谭"
#define CN_X_55 "魔导绪论"
#define CN_X_56 "黑缨枪"
#define CN_X_57 "以理服人"
#define CN_X_58 "沐浴龙血的剑"
#define CN_X_59 "铁影阔剑"
#define CN_X_60 "飞天御剑"
#define CN_X_61 "黎明神剑"
#define CN_X_62 "冷刃"
#define CN_X_63 "温迪"
#define CN_X_64 "可莉"
#define CN_X_65 "达达利亚"
#define CN_X_66 "钟离"
#define CN_X_67 "阿贝多"
#define CN_X_68 "甘雨"
#define CN_X_69 "魈"
#define CN_X_70 "胡桃"
#define CN_X_71 "烟绯"
#define CN_X_72 "优菈"
#define CN_X_73 "尘世之锁"
#define CN_X_74 "贯虹之槊"
#define CN_X_75 "无工之剑"
#define CN_X_76 "斫峰之刃"
#define CN_X_77 "磐岩结绿"
#define CN_X_78 "护摩之杖"
#define CN_X_79 "千岩古剑"
#define CN_X_80 "千岩长枪"
#define CN_X_81 "终末嗟叹之诗"
#define CN_X_82 "暗巷闪光"
#define CN_X_83 "暗巷的酒与诗"
#define CN_X_84 "暗巷猎手"
#define CN_X_85 "松籁响起之时"
#define CN_X_86 "枫原万叶"
#define CN_X_87 "苍古自由之誓"
#define CN_X_88 "幽夜华尔兹"
#define CN_X_89 "神里绫华"
#define CN_X_90 "宵宫"
#define CN_X_91 "早柚"
#define CN_X_92 "雾切之回光"
#define CN_X_93 "飞雷之弦振"
#define CN_X_94 "珊瑚宫心海"
#define CN_X_95 "九条裟罗"
#define CN_X_96 "雷电将军"
#define CN_X_97 "薙草之稻光"
#define CN_X_98 "不灭月华"
#define CN_X_99 "八重神子"
#define CN_X_100 "托马"
#define CN_X_101 "冬极白星"
#define CN_X_102 "曚云之月"
#define CN_X_103 "断浪长鳍"
#define CN_X_104 "恶玉丸"
#define CN_X_105 "荒泷一斗"
#define CN_X_106 "五郎"
#define CN_X_107 "赤角石溃杵"
#define CN_X_108 "云堇"
#define CN_X_109 "申鹤"
#define CN_X_110 "息灾"
#define CN_X_111 "神里绫人"
#define CN_X_112 "神乐之真意"
#define CN_X_113 "波乱月白经津"
#define CN_X_114 "夜兰"
#define CN_X_115 "久岐忍"
#define CN_X_116 "鹿野院平藏"
#define CN_X_117 "若水"
#define CN_X_118 "柯莱"
#define CN_X_119 "提纳里"
#define CN_X_120 "多莉"
#define CN_X_121 "艾尔海森"
#define CN_X_122 "迪希雅"
#define CN_X_123 "妮露"
#define CN_X_124 "纳西妲"
#define CN_X_125 "赛诺"
#define CN_X_126 "坎蒂丝"
#define CN_X_127 "猎人之径"
#define CN_X_128 "Placeholder"
#define CN_X_129 "Placeholder"
#define CN_X_130 "Placeholder"
#define CN_X_131 "Placeholder"
#define CN_X_132 "Placeholder"
#define CN_X_133 "Placeholder"
#define CN_X_134 "Placeholder"
#define CN_X_135 "Placeholder"
#define CN_X_136 "Placeholder"
#define CN_X_137 "Placeholder"
#define CN_X_138 "Placeholder"
#define CN_X_139 "Placeholder"
#define CN_X_140 "Placeholder"
#define CN_X_141 "Placeholder"
#define CN_X_142 "Placeholder"
#define CN_X_143 "Placeholder"
#define CN_X_144 "Placeholder"
#define CN_X_145 "Placeholder"
#define CN_X_146 "Placeholder"
#define CN_X_147 "Placeholder"
#define CN_X_148 "Placeholder"
#define CN_X_149 "Placeholder"
#define CN_X_150 "Placeholder"
#define CN_X_151 "Placeholder"
#define CN_X_152 "Placeholder"
#define CN_X_153 "Placeholder"
#define CN_X_154 "Placeholder"
#define CN_X_155 "Placeholder"
#define CN_X_156 "Placeholder"
#define CN_X_157 "Placeholder"
#define CN_X_158 "Placeholder"
#define CN_X_159 "Placeholder"
#define CN_X_160 "Placeholder"
#define CN_X_161 "Placeholder"
#define CN_X_162 "Placeholder"
#define CN_X_163 "Placeholder"
#define CN_X_164 "Placeholder"
#define CN_X_165 "Placeholder"
#define CN_X_166 "Placeholder"
#define CN_X_167 "Placeholder"
#define CN_X_168 "Placeholder"
#define CN_X_169 "Placeholder"
#define CN_X_170 "Placeholder"
#define CN_X_171 "Placeholder"
#define CN_X_172 "Placeholder"
#define CN_X_173 "Placeholder"
#define CN_X_174 "Placeholder"
#define CN_X_175 "Placeholder"
#define CN_X_176 "Placeholder"
#define CN_X_177 "Placeholder"
#define CN_X_178 "Placeholder"
#define CN_X_179 "Placeholder"
#define CN_X_180 "Placeholder"
#define CN_X_181 "Placeholder"
#define CN_X_182 "Placeholder"
#define CN_X_183 "Placeholder"
#define CN_X_184 "Placeholder"
#define CN_X_185 "Placeholder"
#define CN_X_186 "Placeholder"
#define CN_X_187 "Placeholder"
#define CN_X_188 "Placeholder"
#define CN_X_189 "Placeholder"
#define CN_X_190 "Placeholder"
#define CN_X_191 "Placeholder"
#define CN_X_192 "Placeholder"
#define CN_X_193 "Placeholder"
#define CN_X_194 "Placeholder"
#define CN_X_195 "Placeholder"
#define CN_X_196 "Placeholder"
#define CN_X_197 "Placeholder"
#define CN_X_198 "Placeholder"
#define CN_X_199 "Placeholder"
#define CN_X_200 "Placeholder"
#define CN_X_201 "Placeholder"
#define CN_X_202 "Placeholder"
#define CN_X_203 "Placeholder"
#define CN_X_204 "Placeholder"
#define CN_X_205 "Placeholder"
#define CN_X_206 "Placeholder"
#define CN_X_207 "Placeholder"
#define CN_X_208 "Placeholder"
#define CN_X_209 "Placeholder"
#define CN_X_210 "Placeholder"
#define CN_X_211 "Placeholder"
#define CN_X_212 "Placeholder"
#define CN_X_213 "Placeholder"
#define CN_X_214 "Placeholder"
#define CN_X_215 "Placeholder"
#define CN_X_216 "Placeholder"
#define CN_X_217 "Placeholder"
#define CN_X_218 "Placeholder"
#define CN_X_219 "Placeholder"
#define CN_X_220 "Placeholder"
#define CN_X_221 "Placeholder"
#define CN_X_222 "Placeholder"
#define CN_X_223 "Placeholder"
#define CN_X_224 "Placeholder"
#define CN_X_225 "Placeholder"
#define CN_X_226 "Placeholder"
#define CN_X_227 "Placeholder"
#define CN_X_228 "Placeholder"
#define CN_X_229 "Placeholder"
#define CN_X_230 "Placeholder"
#define CN_X_231 "Placeholder"
#define CN_X_232 "Placeholder"
#define CN_X_233 "Placeholder"
#define CN_X_234 "Placeholder"
#define CN_X_235 "Placeholder"
#define CN_X_236 "Placeholder"
#define CN_X_237 "Placeholder"
#define CN_X_238 "Placeholder"
#define CN_X_239 "Placeholder"
#define CN_X_240 "Placeholder"
#define CN_X_241 "Placeholder"
#define CN_X_242 "Placeholder"
#define CN_X_243 "Placeholder"
#define CN_X_244 "Placeholder"
#define CN_X_245 "Placeholder"
#define CN_X_246 "Placeholder"
#define CN_X_247 "Placeholder"
#define CN_X_248 "Placeholder"
#define CN_X_249 "Placeholder"
#define CN_X_250 "Placeholder"
#define CN_X_251 "Placeholder"
#define CN_X_252 "Placeholder"
#define CN_X_253 "Placeholder"
#define CN_X_254 "Placeholder"
#define CN_X_255 "Placeholder"
#define CN_D_0                                                                                                         \
  "璃月七星之一，玉衡星。对「帝君一言而决的璃月」颇有微词——但实际上，神挺欣赏" \
  "她这样的人。"
#define CN_D_1                                                                                                      \
  "神秘的少女占星术士，声称自己是「伟大的占星术士莫娜」，拥有与名号相符的不俗" \
  "实力，博学而高傲。"
#define CN_D_2                                                                                                      \
  "药庐「不卜庐」的采药姑娘兼学徒，面色苍白如纸的不死之人。话很少，也没有什么" \
  "表情。"
#define CN_D_3 "坐拥蒙德大半酒业的贵公子，财力、人望、能力都令人无法小觑。"
#define CN_D_4 "正直严谨的蒲公英骑士，蒙德西风骑士团的代理团长。"
#define CN_D_5                                                                                                         \
  "极为古老的弓。即使原主不复存在，其中蕴藏之力依旧——那种力量无主，却在万物当" \
  "中。距离心系之物越是遥远，那种力量愈是剧烈。"
#define CN_D_6                                                                                                      \
  "象征风龙身为风之神眷属的大弓。释弦时的鸣声是风之神的偏爱，蕴含苍空与长风的" \
  "力量。"
#define CN_D_7                                                                                                      \
  "崇信风的无名先民所写的教典珍本。数千年流传的信仰之力得到了风的青睐，饱含祝" \
  "福与力量。"
#define CN_D_8                                                                                                      \
  "象征风龙与其主风之神的云图集。细致记载了北地天空的风与云，蕴含苍空与长风的" \
  "力量。"
#define CN_D_9 "魔神翡玉化作的长枪，拥有刺杀远古海兽的沉重与锋利。"
#define CN_D_10 \
  "象征风龙坚定决心的长枪。直挺的枪杆直指天穹，蕴含苍空与长风的力量。"
#define CN_D_11                                                                                                     \
  "狼的骑士所使的大剑。原本只是城中铁匠赠予的厚重的铁片，却在他与狼的情谊中，" \
  "获得神话般的力量。"
#define CN_D_12                                                                                                     \
  "象征风龙的骄傲广布长空的双手剑。挥舞时的低吟是风龙的气势，蕴含苍空与长风的" \
  "力量。"
#define CN_D_13                                                                                                     \
  "象征风龙的荣誉的骑士剑，如今失而复得。剑脊上吹息着风之神的赐福，蕴含苍空与" \
  "长风的力量。"
#define CN_D_14                                                                                                     \
  "西风骑士团的灵魂。历经千年仍在呼唤你卷起正义之风，祓除奸邪，一如上一位挥舞" \
  "此剑的女杰。"
#define CN_D_15 \
  "除了打扮哪里都不像神职人员的修女。冷淡的言行中透着锐利。总是单独行动。"
#define CN_D_16 "璃月港唯一的摇滚乐手，以音乐和热情歌颂着对「成见」的反抗。"
#define CN_D_17 "对万物充满好奇的炼金术士，「生物炼金」学派的研究者。"
#define CN_D_18 "遗传了稀薄的「非人」血统的少女，「猫尾酒馆」的超人气调酒师。"
#define CN_D_19 "驱邪世家出身的年轻方士，为压制自身的「纯阳之体」费尽心思。"
#define CN_D_20 "「西风骑士团」的可靠女仆，梦想有一天能成为正式的骑士。"
#define CN_D_21 "蒙德的冒险家少年，拥有与他的善良毫不相称的霉运。"
#define CN_D_22 "自称「断罪之皇女」，与名为奥兹的漆黑夜鸦同行的神秘少女。"
#define CN_D_23 \
  "「璃月七星」中的「天权」，其名下财富之多，全大陆鲜有人能望其项背。"
#define CN_D_24 "经常能在书摊看到的少年人。手执长剑，胸中常怀侠义之心。"
#define CN_D_25 "武装船队「南十字」的首领，豪快的大姐头。"
#define CN_D_26 \
  "来自璃月，名声在外的少女厨师，对料理之道极具热情，拿手麻辣菜肴堪称一绝。"
#define CN_D_27 "永远充满活力的女孩，骑士团最优秀，同时也是最后的侦察骑士。"
#define CN_D_28                                                                                                     \
  "住在蒙德地区奔狼领，远离城市与人群，和狼一同生活的少年。直觉锐利，身姿迅捷" \
  "。"
#define CN_D_29 "异国面容的剑斗士，西风骑士团的头脑派人物。"
#define CN_D_30 \
  "蒙德城的大家都喜欢芭芭拉。「偶像」这个词是她从一本杂志里看到的。"
#define CN_D_31 "慵懒而博学的图书管理员，须弥教令院「两百年一见」的天才毕业生"
#define CN_D_32 "布满锈迹的铁造大弓，一般人根本拿不动，遑论引弓放矢。"
#define CN_D_33                                                                                                     \
  "在漫长岁月中石化的道具猎弓，上面的仪式性装饰依然清晰可见。拥有受时间之风冲" \
  "刷的祝福力量。"
#define CN_D_34 "曾经作为乐器大放异彩的弓。如今已经不再能令人起舞。"
#define CN_D_35 "西风骑士团的制式反曲弓，只有杰出的弓手能与它的杰出性能相衬。"
#define CN_D_36 "幽暗的琉璃宝珠，传说中拥有洞察人心清白的力量。"
#define CN_D_37                                                                                                     \
  "经历漫长岁月的剧本，记载着的颂词和剧本已经无法辨认。被下了受时间之风侵蚀毁" \
  "坏的诅咒。"
#define CN_D_38 \
  "记载着歌谱的厚重记事簿。尽管遭受了虫蛀和风化，残留的手迹仍透露出力量。"
#define CN_D_39 "西风骑士团的学者间流传的秘典，记载着元素与物质的道理和力量。"
#define CN_D_40 "西风骑士团的制式长枪。枪杆直挺，枪尖轻风流溢。"
#define CN_D_41 "金龙缠绕的长枪，轻快锐利无比。大抵真能轻易屠龙。"
#define CN_D_42 "散发着黯淡荧光的无锋大剑，纯粹以气势和力量碾碎敌人。"
#define CN_D_43                                                                                                     \
  "在漫长岁月中石化的道具大剑，上面的仪式性装饰依然清晰可见。拥有受时间之风冲" \
  "刷的祝福力量。"
#define CN_D_44 "装有时钟的厚重大剑，其中的计时机关早已被破坏。"
#define CN_D_45 "西风骑士团的重型仪式剑。能轻易导出元素力量，具有卓越的破坏力。"
#define CN_D_46 "雕饰浮华的利刃，却丝毫不损它的柔韧与锋锐。破空之声有如龙吟。"
#define CN_D_47                                                                                                     \
  "在漫长岁月中石化的道具剑，上面的仪式性装饰依然清晰可见。拥有受时间之风冲刷" \
  "的祝福力量。"
#define CN_D_48 "细剑的锈迹下透露出原本华丽的装饰，挥舞时轻若无物。"
#define CN_D_49 "西风骑士团的制式长剑。轻快锐利之余，也能轻易导出元素力量。"
#define CN_D_50                                                                                                     \
  "其实就是一把弓。在无数的改进和实验中，发明出究极弹弓的人发现自己做了一把弓" \
  "。"
#define CN_D_51                                                                                                     \
  "据说曾属于技艺高强的射手，是一把上好的弓。因为散发出强烈的气息，难以用于狩" \
  "猎。"
#define CN_D_52 \
  "相传渡鸦是死的使者。将鸦羽装饰在弓臂上，射出的每一箭都宣告着猎物的终末。"
#define CN_D_53                                                                                                     \
  "由璃月北郊绝云间出产的硬玉雕琢而成的法器。小巧轻盈，经久耐用，江湖人称「翡" \
  "玉丸」。"
#define CN_D_54                                                                                                     \
  "五名英雄踏上屠龙征途的虚构故事。文笔很差，结构散乱。失败的教训是这本书所拥" \
  "有的伟大力量。"
#define CN_D_55 "第十二版。结合时代发展加注了新内容，并修订了第十一版的错别字。"
#define CN_D_56 "解决了白缨容易弄脏问题的绝世好枪。"
#define CN_D_57 "精钢打造的趁手大铁棒子。最好的理论依据。"
#define CN_D_58                                                                                                     \
  "据说是北方英雄浸过龙血的钢铁大剑，有刀枪不入的神力…这种护佑并不会延伸到挥" \
  "舞它的人身上。"
#define CN_D_59                                                                                                     \
  "这把剑是著名的光之狮艾伦德林的佩剑的仿品。握紧它，感受传说中大英雄的力量吧" \
  "！注意：幻想请适度。"
#define CN_D_60 "可靠的钢剑，传说著名的「御剑公子」曾试图借助它飞天。"
#define CN_D_61                                                                                                     \
  "一把曾经耀若朝阳的宝剑，掌握它的人会获得「自我感觉良好」的力量加持。剑身上" \
  "的发光材料已经褪去。"
#define CN_D_62 "多层锻打的精钢铸就的可靠兵器，曾见证旧主诸多冒险奇谭。"
#define CN_D_63 "蒙德城诸多吟游诗人中的一位，自由自在地穿行在街头巷尾。"
#define CN_D_64 "西风骑士团禁闭室的常客，蒙德的爆破大师。人称「逃跑的太阳」。"
#define CN_D_65 "愚人众执行官第十一位，「公子」，其战绩威名远扬。"
#define CN_D_66 "被「往生堂」请来的神秘客人，知识渊博，对各种事物都颇有见地。"
#define CN_D_67 \
  "西风骑士团首席炼金术士兼调查小队队长，被称做「白垩之子」的天才。"
#define CN_D_68 "月海亭的秘书，体内流淌着仙兽「麒麟」的血脉。"
#define CN_D_69 \
  "守护璃月的仙人，「夜叉」。美号「降魔大圣」，妙称「护法夜叉大将」。"
#define CN_D_70 "「往生堂」七十七代堂主，年纪轻轻就已主掌璃月的葬仪事务。"
#define CN_D_71 "活跃在璃月港的知名律法咨询师，混有仙兽血脉的精明少女。"
#define CN_D_72                                                                                                     \
  "古老家族出身的「浪花骑士」，西风骑士团游击小队队长。身为旧贵族后裔却加入了" \
  "堪称死对头的西风骑士团，该事件至今仍是蒙德一大谜团。"
#define CN_D_73 "蕴含着某种悠远记忆的石锁，随着无穷的变换透露出其中的力量。"
#define CN_D_74 \
  "或许能贯穿一切的锋利长枪。挥舞当中，仿佛能见到空气被枪尖划破的裂痕。"
#define CN_D_75 "能靖祛妖魔奸佞，仿佛有神威的无锋大剑。"
#define CN_D_76 "传说中象征着某一则特定契约的利刃，曾经斩落过山岳的尖端。"
#define CN_D_77 "由纯净的翠玉精琢细雕而成的仪礼宝剑，挥舞时剑风中似有叹息之声。"
#define CN_D_78 "在早已失落的古老祭仪中，使用的朱赤「柴火杖」。"
#define CN_D_79 "以璃月的基岩为原料削凿成的厚重大剑。"
#define CN_D_80 "取孤云阁的岩片精工打造的长枪，枪尖坚固无比。"
#define CN_D_81 "如同诗人的乐器一般优美的弓，放出的箭矢如同叹息声一般穿透人心。"
#define CN_D_82 "有着黑夜颜色的笔直长剑，曾属于穿行于暗巷的盗贼。"
#define CN_D_83 \
  "过去贵族时代流行的歌谱，作者已无从考究。其中记载了某位侠盗的故事…"
#define CN_D_84 "外形精巧奢华的长弓，曾属于某位从未被抓获的义贼。"
#define CN_D_85 \
  "如同翻弄草木的息吹一般轻盈的大剑，如同吹倒树木的飓风一般摧枯拉朽的武器。"
#define CN_D_86                                                                                                     \
  "来自稻妻的浪人武士，如今栖身于璃月船队「南十字」中。性情温和而洒脱，心中埋" \
  "藏着许多往事。"
#define CN_D_87 \
  "如同悠古的歌声一般苍蓝的直剑，如同风之国土自由的誓言一般锐利的武器。"
#define CN_D_88 "有着如同罪与幻想之夜一般颜色的弓。"
#define CN_D_89 "稻妻「社奉行」神里家的大小姐。端庄而文雅，聪慧又坚韧。"
#define CN_D_90 \
  "「长野原烟花店」店长，「夏祭的女王」，将人们的愿望寄托于烟花中的能工巧匠。"
#define CN_D_91 "隶属于「终末番」的忍者。身形小巧，总像没睡饱一样。"
#define CN_D_92 "闪烁着凄烈紫光的太刀。名之为「回光」是因为一度破碎的过去。"
#define CN_D_93 "曾由将军御赐的长弓，闪烁着永不熄灭的雷光。"
#define CN_D_94 "海祇岛的「现人神巫女」，统管海祇岛各项事宜的少女。"
#define CN_D_95 "「天领奉行」的大将，杀伐果断，骁勇善战。"
#define CN_D_96 "其身为御建鸣神主尊大御所大人，许稻妻人民以亘古不变之「永恒」。"
#define CN_D_97 "用于「斩草」的薙刀。对向此物之军势，也会如苇草般倒下吧…"
#define CN_D_98 "出自深海的美玉之环，闪烁着清澈如月的光泽，一如遥远往昔。"
#define CN_D_99                                                                                                     \
  "鸣神大社的宫司大人，兼任「八重堂」总编。艳丽动人的外表下藏着令人意想不到的" \
  "聪慧与狡黠。"
#define CN_D_100 "神里家的家政官，活跃在稻妻的「地头蛇」。"
#define CN_D_101 "如同深冬坚冰一样尖锐的无垢之弓。"
#define CN_D_102 "出自螺钿与珊瑚的精美战弓，月色的弓臂上流动着凄然的光彩。"
#define CN_D_103 "以海渊之下的闪亮材质打造而成的薙刀，一度曾为天狗一族所有。"
#define CN_D_104 \
  "传说中「恶王」的爱刀，刀身庞大雄伟，但挥舞起来却出乎意料地轻便。"
#define CN_D_105                                                                                                    \
  "活跃在稻妻城花见坂的「荒泷派」初代目头领。什么，从没听说过荒泷派？你是想找" \
  "茬吗？"
#define CN_D_106 "海祇岛军的大将，深受部下信赖。"
#define CN_D_107                                                                                                    \
  "依据过去的主人的说法，这是何等鬼怪精妖都能打跑的大杵「赤角石见石溃金涂金啮" \
  "御狮子」。"
#define CN_D_108 \
  "集剧作与演唱能力于一身的璃月戏曲名角。风格自成一派，雅致柔美，恰如其人。"
#define CN_D_109 \
  "气质出尘的仙家子弟。隐修在璃月群山之间，个性也如仙人般淡漠疏离。"
#define CN_D_110 "由奇异晶石打造成的锋锐利器。幽幽蓝光似乎诉说着无尽往事。"
#define CN_D_111 "社奉行神里家年轻有为的现任家主，为人温雅有礼，处事颇有手段。"
#define CN_D_112 "表演神乐之舞时所用的神铃，为宫司所赐福。神樱之香萦绕其上。"
#define CN_D_113 \
  "经津传奉命锻造的名作。因其如汹涌海涛般的气度，而得「波乱」之名。"
#define CN_D_114 \
  "自称供职于总务司的神秘人士，却又是总务司名录里的「不存在之人」。"
#define CN_D_115                                                                                                       \
  "干练可靠的「荒泷派」的副手——特别注明：干练可靠形容的不是「荒泷派」而是副手" \
  "。"
#define CN_D_116 "天领奉行的天才少年侦探，直觉敏锐，心思玲珑。"
#define CN_D_117 "色泽流移难测的长弓，在光下显现着如水的润蓝。"
#define CN_D_118 "柯莱"
#define CN_D_119 "提纳里"
#define CN_D_120 "多莉"
#define CN_D_121 "艾尔海森"
#define CN_D_122 "迪希雅"
#define CN_D_123 "妮露"
#define CN_D_124 "纳西妲"
#define CN_D_125 "赛诺"
#define CN_D_126 "坎蒂丝"
#define CN_D_127 "猎人之径"
#define CN_D_128 "Placeholder"
#define CN_D_129 "Placeholder"
#define CN_D_130 "Placeholder"
#define CN_D_131 "Placeholder"
#define CN_D_132 "Placeholder"
#define CN_D_133 "Placeholder"
#define CN_D_134 "Placeholder"
#define CN_D_135 "Placeholder"
#define CN_D_136 "Placeholder"
#define CN_D_137 "Placeholder"
#define CN_D_138 "Placeholder"
#define CN_D_139 "Placeholder"
#define CN_D_140 "Placeholder"
#define CN_D_141 "Placeholder"
#define CN_D_142 "Placeholder"
#define CN_D_143 "Placeholder"
#define CN_D_144 "Placeholder"
#define CN_D_145 "Placeholder"
#define CN_D_146 "Placeholder"
#define CN_D_147 "Placeholder"
#define CN_D_148 "Placeholder"
#define CN_D_149 "Placeholder"
#define CN_D_150 "Placeholder"
#define CN_D_151 "Placeholder"
#define CN_D_152 "Placeholder"
#define CN_D_153 "Placeholder"
#define CN_D_154 "Placeholder"
#define CN_D_155 "Placeholder"
#define CN_D_156 "Placeholder"
#define CN_D_157 "Placeholder"
#define CN_D_158 "Placeholder"
#define CN_D_159 "Placeholder"
#define CN_D_160 "Placeholder"
#define CN_D_161 "Placeholder"
#define CN_D_162 "Placeholder"
#define CN_D_163 "Placeholder"
#define CN_D_164 "Placeholder"
#define CN_D_165 "Placeholder"
#define CN_D_166 "Placeholder"
#define CN_D_167 "Placeholder"
#define CN_D_168 "Placeholder"
#define CN_D_169 "Placeholder"
#define CN_D_170 "Placeholder"
#define CN_D_171 "Placeholder"
#define CN_D_172 "Placeholder"
#define CN_D_173 "Placeholder"
#define CN_D_174 "Placeholder"
#define CN_D_175 "Placeholder"
#define CN_D_176 "Placeholder"
#define CN_D_177 "Placeholder"
#define CN_D_178 "Placeholder"
#define CN_D_179 "Placeholder"
#define CN_D_180 "Placeholder"
#define CN_D_181 "Placeholder"
#define CN_D_182 "Placeholder"
#define CN_D_183 "Placeholder"
#define CN_D_184 "Placeholder"
#define CN_D_185 "Placeholder"
#define CN_D_186 "Placeholder"
#define CN_D_187 "Placeholder"
#define CN_D_188 "Placeholder"
#define CN_D_189 "Placeholder"
#define CN_D_190 "Placeholder"
#define CN_D_191 "Placeholder"
#define CN_D_192 "Placeholder"
#define CN_D_193 "Placeholder"
#define CN_D_194 "Placeholder"
#define CN_D_195 "Placeholder"
#define CN_D_196 "Placeholder"
#define CN_D_197 "Placeholder"
#define CN_D_198 "Placeholder"
#define CN_D_199 "Placeholder"
#define CN_D_200 "Placeholder"
#define CN_D_201 "Placeholder"
#define CN_D_202 "Placeholder"
#define CN_D_203 "Placeholder"
#define CN_D_204 "Placeholder"
#define CN_D_205 "Placeholder"
#define CN_D_206 "Placeholder"
#define CN_D_207 "Placeholder"
#define CN_D_208 "Placeholder"
#define CN_D_209 "Placeholder"
#define CN_D_210 "Placeholder"
#define CN_D_211 "Placeholder"
#define CN_D_212 "Placeholder"
#define CN_D_213 "Placeholder"
#define CN_D_214 "Placeholder"
#define CN_D_215 "Placeholder"
#define CN_D_216 "Placeholder"
#define CN_D_217 "Placeholder"
#define CN_D_218 "Placeholder"
#define CN_D_219 "Placeholder"
#define CN_D_220 "Placeholder"
#define CN_D_221 "Placeholder"
#define CN_D_222 "Placeholder"
#define CN_D_223 "Placeholder"
#define CN_D_224 "Placeholder"
#define CN_D_225 "Placeholder"
#define CN_D_226 "Placeholder"
#define CN_D_227 "Placeholder"
#define CN_D_228 "Placeholder"
#define CN_D_229 "Placeholder"
#define CN_D_230 "Placeholder"
#define CN_D_231 "Placeholder"
#define CN_D_232 "Placeholder"
#define CN_D_233 "Placeholder"
#define CN_D_234 "Placeholder"
#define CN_D_235 "Placeholder"
#define CN_D_236 "Placeholder"
#define CN_D_237 "Placeholder"
#define CN_D_238 "Placeholder"
#define CN_D_239 "Placeholder"
#define CN_D_240 "Placeholder"
#define CN_D_241 "Placeholder"
#define CN_D_242 "Placeholder"
#define CN_D_243 "Placeholder"
#define CN_D_244 "Placeholder"
#define CN_D_245 "Placeholder"
#define CN_D_246 "Placeholder"
#define CN_D_247 "Placeholder"
#define CN_D_248 "Placeholder"
#define CN_D_249 "Placeholder"
#define CN_D_250 "Placeholder"
#define CN_D_251 "Placeholder"
#define CN_D_252 "Placeholder"
#define CN_D_253 "Placeholder"
#define CN_D_254 "Placeholder"
#define CN_D_255 "Placeholder"
#define CN_CBI_0 "Placeholder"
#define CN_CBI_1 "杯装之诗_20200928-20201018 (温迪, 芭芭拉, 菲谢尔, 香菱)"
#define CN_CBI_2 "闪焰的驻足_20201020-20201110 (可莉, 行秋, 诺艾尔, 砂糖)"
#define CN_CBI_3 "暂别冬都_20201111-20201201 (达达利亚, 迪奥娜, 北斗, 凝光)"
#define CN_CBI_4 "陵薮市朝_20201201-20201222 (钟离, 辛焱, 雷泽, 重云)"
#define CN_CBI_5 "深秘之息_20201223-20210112 (阿贝多, 菲谢尔, 砂糖, 班尼特)"
#define CN_CBI_6 "浮生孰来_20210112-20210202 (甘雨, 香菱, 行秋, 诺艾尔)"
#define CN_CBI_7 "烟火之邀_20210203-20210217 (魈, 迪奥娜, 北斗, 辛焱)"
#define CN_CBI_8 "鱼龙灯昼_20210217-20210302 (刻晴, 凝光, 班尼特, 芭芭拉)"
#define CN_CBI_9 "赤团开时_20210302-20210316 (胡桃, 行秋, 香菱, 重云)"
#define CN_CBI_10 "杯装之诗_20210317-20210406 (温迪, 砂糖, 雷泽, 诺艾尔)"
#define CN_CBI_11 \
  "暂别冬都_20210406-20210427 (达达利亚, 罗莎莉亚, 芭芭拉, 菲谢尔)"
#define CN_CBI_12 "陵薮市朝_20210428-20210518 (钟离, 烟绯, 诺艾尔, 迪奥娜)"
#define CN_CBI_13 "浪涌之瞬_20210518-20210608 (优菈, 辛焱, 行秋, 北斗)"
#define CN_CBI_14 "闪焰的驻足_20210608-20210629 (可莉, 砂糖, 菲谢尔, 芭芭拉)"
#define CN_CBI_15 \
  "叶落风随_20210629-20210720 (枫原万叶, 罗莎莉亚, 班尼特, 雷泽)"
#define CN_CBI_16 "白鹭之庭_20210721-20210810 (神里绫华, 烟绯, 凝光, 重云)"
#define CN_CBI_17 "焰色天河_20210810-20210831 (宵宫, 早柚, 迪奥娜, 辛焱)"
#define CN_CBI_18 \
  "影寂天下人_20210901-20210921 (雷电将军, 九条裟罗, 香菱, 砂糖)"
#define CN_CBI_19 \
  "浮岳虹珠_20210921-20211012 (珊瑚宫心海, 罗莎莉亚, 北斗, 行秋)"
#define CN_CBI_20 "暂别冬都_20211013-20211102 (达达利亚, 凝光, 重云, 烟绯)"
#define CN_CBI_21 "赤团开时_20211102-20211123 (胡桃, 托马, 迪奥娜, 早柚)"
#define CN_CBI_22 \
  "深秘之息_20211124-20211214 (阿贝多, 罗莎莉亚, 诺艾尔, 班尼特)"
#define CN_CBI_23 "鬼门斗宴_20211214-20220104 (荒泷一斗, 五郎, 香菱, 芭芭拉)"
#define CN_CBI_24 "出尘入世_20220105-20220125 (申鹤, 云堇, 凝光, 重云)"
#define CN_CBI_25 "陵薮市朝_20220125-20220215 (钟离, 烟绯, 行秋, 北斗)"
#define CN_CBI_26 "华紫樱绯_20220216-20220308 (八重神子, 菲谢尔, 迪奥娜, 托马)"
#define CN_CBI_27 \
  "影寂天下人_20220308-20220329 (雷电将军, 班尼特, 辛焱, 九条裟罗)"
#define CN_CBI_28 "苍流踏花_20220330-20220419 (神里绫人, 云堇, 砂糖, 香菱)"
#define CN_CBI_29 "白鹭之庭_20220419-20220531 (神里绫华, 早柚, 雷泽, 罗莎莉亚)"
#define CN_CBI_30 "素霓伣天_20220531-20220621 (夜兰, 芭芭拉, 烟绯, 诺艾尔)"
#define CN_CBI_31 "鬼门斗宴_20220621-20220712 (荒泷一斗, 久岐忍, 重云, 五郎)"
#define CN_CBI_32 \
  "叶落风随_20220713-20220802 (枫原万叶, 鹿野院平藏, 凝光, 托马)"
#define CN_CBI_33 "焰色天河_20220802-20220823 (宵宫, 班尼特, 辛焱, 云堇)"
#define CN_CBI_34 "巡御蘙荟_20220824-20220909 (提纳里, 柯莱, 迪奥娜, 菲谢尔)"
#define CN_CBI_35 "Placeholder"
#define CN_CBI_36 "Placeholder"
#define CN_CBI_37 "Placeholder"
#define CN_CBI_38 "Placeholder"
#define CN_CBI_39 "Placeholder"
#define CN_CBI_40 "Placeholder"
#define CN_CBI_41 "Placeholder"
#define CN_CBI_42 "Placeholder"
#define CN_CBI_43 "Placeholder"
#define CN_CBI_44 "Placeholder"
#define CN_CBI_45 "Placeholder"
#define CN_CBI_46 "Placeholder"
#define CN_CBI_47 "Placeholder"
#define CN_CBI_48 "Placeholder"
#define CN_CBI_49 "Placeholder"
#define CN_CBI_50 "Placeholder"
#define CN_CBI_51 "Placeholder"
#define CN_CBI_52 "Placeholder"
#define CN_CBI_53 "Placeholder"
#define CN_CBI_54 "Placeholder"
#define CN_CBI_55 "Placeholder"
#define CN_CBI_56 "Placeholder"
#define CN_CBI_57 "Placeholder"
#define CN_CBI_58 "Placeholder"
#define CN_CBI_59 "Placeholder"
#define CN_CBI_60 "Placeholder"
#define CN_CBI_61 "Placeholder"
#define CN_CBI_62 "Placeholder"
#define CN_CBI_63 "Placeholder"
#define CN_CBII_0 "Placeholder"
#define CN_CBII_1 "浪涌之瞬_20211124-20211214 (优菈, 罗莎莉亚, 诺艾尔, 班尼特)"
#define CN_CBII_2 "烟火之邀_20220105-20220125 (魈, 云堇, 凝光, 重云)"
#define CN_CBII_3 "浮生孰来_20220125-20220215 (甘雨, 烟绯, 行秋, 北斗)"
#define CN_CBII_4 \
  "浮岳虹珠_20220308-20220329 (珊瑚宫心海, 班尼特, 辛焱, 九条裟罗)"
#define CN_CBII_5 "杯装之诗_20220330-20220419 (温迪, 云堇, 砂糖, 香菱)"
#define CN_CBII_6 "烟火之邀_20220531-20220621 (魈, 芭芭拉, 烟绯, 诺艾尔)"
#define CN_CBII_7 "闪焰的驻足_20220713-20220802 (可莉, 鹿野院平藏, 凝光, 托马)"
#define CN_CBII_8 "陵薮市朝_20220824-20220909 (钟离, 柯莱, 迪奥娜, 菲谢尔)"
#define CN_CBII_9 "Placeholder"
#define CN_CBII_10 "Placeholder"
#define CN_CBII_11 "Placeholder"
#define CN_CBII_12 "Placeholder"
#define CN_CBII_13 "Placeholder"
#define CN_CBII_14 "Placeholder"
#define CN_CBII_15 "Placeholder"
#define CN_CBII_16 "Placeholder"
#define CN_CBII_17 "Placeholder"
#define CN_CBII_18 "Placeholder"
#define CN_CBII_19 "Placeholder"
#define CN_CBII_20 "Placeholder"
#define CN_CBII_21 "Placeholder"
#define CN_CBII_22 "Placeholder"
#define CN_CBII_23 "Placeholder"
#define CN_CBII_24 "Placeholder"
#define CN_CBII_25 "Placeholder"
#define CN_CBII_26 "Placeholder"
#define CN_CBII_27 "Placeholder"
#define CN_CBII_28 "Placeholder"
#define CN_CBII_29 "Placeholder"
#define CN_CBII_30 "Placeholder"
#define CN_CBII_31 "Placeholder"
#define CN_WB_0 "Placeholder"
#define CN_WB_1                                                                                \
  "神铸赋形_20200928-20201018 (风鹰剑, 阿莫斯之弓, 笛剑, 钟剑, 流浪乐章, " \
  "绝弦, 西风长枪)"
#define CN_WB_2                                                                                      \
  "神铸赋形_20201020-20201109 (四风原典, 狼的末路, 祭礼剑, 祭礼弓, 祭礼大剑, " \
  "祭礼残章, 匣里灭辰)"
#define CN_WB_3                                                                          \
  "神铸赋形_20201111-20201201 (尘世之锁, 天空之翼, 雨裁, 昭心, 弓藏, " \
  "西风长枪, 笛剑)"
#define CN_WB_4                                                                                      \
  "神铸赋形_20201201-20201222 (贯虹之槊, 无工之剑, 匣里龙吟, 钟剑, 西风秘典, " \
  "西风猎弓, 匣里灭辰)"
#define CN_WB_5                                                                           \
  "神铸赋形_20201223-20210112 (斫峰之刃, 天空之卷, 西风剑, 西风大剑, " \
  "西风长枪, 祭礼残章, 绝弦)"
#define CN_WB_6                                                                                      \
  "神铸赋形_20210112-20210202 (天空之傲, 阿莫斯之弓, 祭礼剑, 钟剑, 匣里灭辰, " \
  "昭心, 西风猎弓)"
#define CN_WB_7                                                                             \
  "神铸赋形_20210203-20210223 (磐岩结绿, 和璞鸢, 弓藏, 昭心, 西风长枪, " \
  "祭礼大剑, 笛剑)"
#define CN_WB_8                                                                              \
  "神铸赋形_20210223-20210316 (护摩之杖, 狼的末路, 千岩古剑, 千岩长枪, " \
  "祭礼弓, 流浪乐章, 匣里龙吟)"
#define CN_WB_9                                                                      \
  "神铸赋形_20210317-20210406 (终末嗟叹之诗, 天空之刃, 暗巷闪光, " \
  "暗巷的酒与诗, 西风大剑, 西风猎弓, 匣里灭辰)"
#define CN_WB_10                                                                          \
  "神铸赋形_20210406-20210427 (天空之翼, 四风原典, 暗巷猎手, 西风剑, " \
  "祭礼大剑, 西风秘典, 西风长枪)"
#define CN_WB_11                                                                                     \
  "神铸赋形_20210428-20210518 (斫峰之刃, 尘世之锁, 笛剑, 千岩古剑, 千岩长枪, " \
  "昭心, 祭礼弓)"
#define CN_WB_12                                                                                     \
  "神铸赋形_20210518-20210608 (松籁响起之时, 风鹰剑, 祭礼剑, 雨裁, 匣里灭辰, " \
  "祭礼残章, 弓藏)"
#define CN_WB_13                                                                                \
  "神铸赋形_20210609-20210629 (天空之傲, 四风原典, 幽夜华尔兹, 匣里龙吟, " \
  "钟剑, 西风长枪, 流浪乐章)"
#define CN_WB_14                                                                     \
  "神铸赋形_20210629-20210720 (苍古自由之誓, 天空之卷, 暗巷闪光, " \
  "暗巷的酒与诗, 暗巷猎手, 西风大剑, 匣里灭辰)"
#define CN_WB_15                                                                                     \
  "神铸赋形_20210721-20210810 (雾切之回光, 天空之脊, 绝弦, 西风剑, 西风长枪, " \
  "西风秘典, 祭礼大剑)"
#define CN_WB_16                                                                             \
  "神铸赋形_20210810-20210831 (飞雷之弦振, 天空之刃, 西风猎弓, 祭礼剑, " \
  "匣里灭辰, 雨裁, 祭礼残章)"
#define CN_WB_17                                                                             \
  "神铸赋形_20210901-20210921 (薙草之稻光, 无工之剑, 祭礼弓, 匣里龙吟, " \
  "流浪乐章, 西风长枪, 钟剑)"
#define CN_WB_18                                                                                     \
  "神铸赋形_20210921-20211012 (不灭月华, 磐岩结绿, 笛剑, 西风大剑, 匣里灭辰, " \
  "西风秘典, 绝弦)"
#define CN_WB_19                                                                                     \
  "神铸赋形_20211013-20211102 (冬极白星, 尘世之锁, 恶玉丸, 西风剑, 西风长枪, " \
  "昭心, 弓藏)"
#define CN_WB_20                                                                                   \
  "神铸赋形_20211102-20211123 (护摩之杖, 终末嗟叹之诗, 断浪长鳍, 曚云之月, " \
  "祭礼剑, 雨裁, 流浪乐章)"
#define CN_WB_21                                                                           \
  "神铸赋形_20211124-20211214 (苍古自由之誓, 松籁响起之时, 暗巷猎手, " \
  "匣里龙吟, 匣里灭辰, 暗巷的酒与诗, 祭礼大剑)"
#define CN_WB_22                                                                                   \
  "神铸赋形_20211214-20210104 (赤角石溃杵, 天空之翼, 暗巷闪光, 幽夜华尔兹, " \
  "西风长枪, 祭礼残章, 钟剑)"
#define CN_WB_23                                                                            \
  "神铸赋形_20220105-20220125 (息灾, 和璞鸢, 千岩长枪, 笛剑, 西风猎弓, " \
  "流浪乐章, 西风大剑)"
#define CN_WB_24                                                                             \
  "神铸赋形_20220125-20220215 (贯虹之槊, 阿莫斯之弓, 千岩古剑, 西风剑, " \
  "匣里灭辰, 西风秘典, 祭礼弓)"
#define CN_WB_25                                                                                     \
  "神铸赋形_20220216-20220308 (神乐之真意, 磐岩结绿, 断浪长鳍, 绝弦, 祭礼剑, " \
  "昭心, 雨裁)"
#define CN_WB_26                                                                             \
  "神铸赋形_20220308-20220329 (薙草之稻光, 不灭月华, 恶玉丸, 曚云之月, " \
  "匣里龙吟, 西风长枪, 祭礼残章)"
#define CN_WB_27                                                                             \
  "神铸赋形_20220330-20220419 (波乱月白经津, 终末嗟叹之诗, 弓藏, 笛剑, " \
  "流浪乐章, 匣里灭辰, 祭礼大剑)"
#define CN_WB_28                                                                             \
  "神铸赋形_20220419-20220531 (雾切之回光, 无工之剑, 西风猎弓, 西风剑, " \
  "西风长枪, 西风秘典, 钟剑)"
#define CN_WB_29                                                                            \
  "神铸赋形_20220531-20220621 (若水, 和璞鸢, 千岩长枪, 昭心, 西风大剑, " \
  "祭礼弓, 祭礼剑)"
#define CN_WB_30                                                                                \
  "神铸赋形_20220621-20220712 (赤角石溃杵, 尘世之锁, 千岩古剑, 匣里龙吟, " \
  "匣里灭辰, 祭礼残章, 绝弦)"
#define CN_WB_31                                                                                      \
  "神铸赋形_20220713-20220802 (苍古自由之誓, 四风原典, 暗巷闪光, 幽夜华尔兹, " \
  "雨裁, 西风长枪, 流浪乐章)"
#define CN_WB_32                                                                                      \
  "神铸赋形_20220802-20220823 (飞雷之弦振, 斫峰之刃, 暗巷的酒与诗, 暗巷猎手, " \
  "笛剑, 祭礼大剑, 匣里灭辰)"
#define CN_WB_33                                                                    \
  "神铸赋形_20220824-20220909 (猎人之径, 贯虹之槊, 西风剑, 钟剑, " \
  "西风长枪, 西风秘典, 绝弦)"
#define CN_WB_34 "Placeholder"
#define CN_WB_35 "Placeholder"
#define CN_WB_36 "Placeholder"
#define CN_WB_37 "Placeholder"
#define CN_WB_38 "Placeholder"
#define CN_WB_39 "Placeholder"
#define CN_WB_40 "Placeholder"
#define CN_WB_41 "Placeholder"
#define CN_WB_42 "Placeholder"
#define CN_WB_43 "Placeholder"
#define CN_WB_44 "Placeholder"
#define CN_WB_45 "Placeholder"
#define CN_WB_46 "Placeholder"
#define CN_WB_47 "Placeholder"
#define CN_WB_48 "Placeholder"
#define CN_WB_49 "Placeholder"
#define CN_WB_50 "Placeholder"
#define CN_WB_51 "Placeholder"
#define CN_WB_52 "Placeholder"
#define CN_WB_53 "Placeholder"
#define CN_WB_54 "Placeholder"
#define CN_WB_55 "Placeholder"
#define CN_WB_56 "Placeholder"
#define CN_WB_57 "Placeholder"
#define CN_WB_58 "Placeholder"
#define CN_WB_59 "Placeholder"
#define CN_WB_60 "Placeholder"
#define CN_WB_61 "Placeholder"
#define CN_WB_62 "Placeholder"
#define CN_WB_63 "Placeholder"
#define CN_PB_0 "Placeholder"
#define CN_PB_1 "奔行世间_20200928-20201222 (公测)"
#define CN_PB_2 "奔行世间_20201223-20210427 (新增迪奥娜和辛焱)"
#define CN_PB_3 "奔行世间_20210428-20210608 (新增罗莎莉亚)"
#define CN_PB_4 "奔行世间_20210609-20210901 (新增烟绯)"
#define CN_PB_5 "奔行世间_20210901-20211012 (新增早柚)"
#define CN_PB_6 "奔行世间_20211013-20211123 (新增九条裟罗)"
#define CN_PB_7 "奔行世间_20211124-20220104 (新增托马)"
#define CN_PB_8 "奔行世间_20220105-20220215 (新增五郎)"
#define CN_PB_9 "奔行世间_20220216-20220712 (新增云堇)"
#define CN_PB_10 "奔行世间_20220713-20220823 (新增久岐忍)"
#define CN_PB_11 "奔行世间_20220824-20220927 (新增鹿野院平藏)"
#define CN_PB_12 "奔行世间_20220928- (新增提纳里和柯莱)"
#define CN_PB_13 "Placeholder"
#define CN_PB_14 "Placeholder"
#define CN_PB_15 "Placeholder"
#define CN_PB_16 "Placeholder"
#define CN_PB_17 "Placeholder"
#define CN_PB_18 "Placeholder"
#define CN_PB_19 "Placeholder"
#define CN_PB_20 "Placeholder"
#define CN_PB_21 "Placeholder"
#define CN_PB_22 "Placeholder"
#define CN_PB_23 "Placeholder"
#define CN_PB_24 "Placeholder"
#define CN_PB_25 "Placeholder"
#define CN_PB_26 "Placeholder"
#define CN_PB_27 "Placeholder"
#define CN_PB_28 "Placeholder"
#define CN_PB_29 "Placeholder"
#define CN_PB_30 "Placeholder"
#define CN_PB_31 "Placeholder"
#define CN_BW_0 "Placeholder"
#define CN_BW_1 "新手祈愿_20200928-(公测)"
#define CN_BW_2 "Placeholder"
#define CN_BW_3 "Placeholder"
#define CN_BW_4 "Placeholder"
#define CN_BW_5 "Placeholder"
#define CN_BW_6 "Placeholder"
#define CN_BW_7 "Placeholder"
#define CN_V_0 "1.0版本 全球同步公测"
#define CN_V_1 "1.1版本 「迫近的客星」"
#define CN_V_2 "1.2版本 「白垩与黑龙」"
#define CN_V_3 "1.3版本 「明霄升海平」"
#define CN_V_4 "1.4版本 「风花的邀约」"
#define CN_V_5 "1.5版本 「玉扉绕尘歌」"
#define CN_V_6 "1.6版本 「盛夏！海岛？大冒险！」"
#define CN_V_7 "2.0版本 「不动鸣神，泡影断灭」"
#define CN_V_8 "2.1版本 「韶光抚月，天下人间」"
#define CN_V_9 "2.2版本 「雾海悬谜境」"
#define CN_V_10 "2.3版本 「皑尘与雪影」"
#define CN_V_11 "2.4版本 「飞彩镌流年」"
#define CN_V_12 "2.5版本 「薄樱初绽时」"
#define CN_V_13 "2.6版本 「流风眷堇庭」"
#define CN_V_14 "2.7版本 「荒梦藏虞渊」"
#define CN_V_15 "2.8版本 「仲夏！幻夜？奇想曲！」"
#define CN_V_16 "3.0版本 「千朵玫瑰带来的黎明」"
#define CN_V_17 "Placeholder"
#define CN_V_18 "Placeholder"
#define CN_V_19 "Placeholder"
#define CN_V_20 "Placeholder"
#define CN_V_21 "Placeholder"
#define CN_V_22 "Placeholder"
#define CN_V_23 "Placeholder"
#define CN_V_24 "Placeholder"
#define CN_V_25 "Placeholder"
#define CN_V_26 "Placeholder"
#define CN_V_27 "Placeholder"
#define CN_V_28 "Placeholder"
#define CN_V_29 "Placeholder"
#define CN_V_30 "Placeholder"
#define CN_V_31 "Placeholder"

#endif

#endif
